export default [
  {
    adult: false,
    backdrop_path: "/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
    genre_ids: [28, 35],
    id: 897087,
    original_language: "en",
    original_title: "Freelance",
    overview:
      "Một cựu chỉ huy lực lượng đặc biệt đảm nhận nhiệm vụ bảo vệ an ninh cho một nhà báo trong cuộc phỏng vấn tên độc tài. Nhưng khi cuộc đảo chính quân sự nổ ra, cả hai bị đẩy vào cuộc rượt đuổi khốc liệt, phải chiến đấu để giữ tính mạng.",
    popularity: 1834.492,
    poster_path: "/zDb5YeHSGGMlS6eqhUXcVU2OzAJ.jpg",
    release_date: "2023-10-05",
    title: "Đặc Vụ Tự Do",
    video: false,
    vote_average: 6.4,
    vote_count: 204,
  },
  {
    adult: false,
    backdrop_path: "/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
    genre_ids: [80, 18, 36],
    id: 466420,
    original_language: "en",
    original_title: "Killers of the Flower Moon",
    overview:
      "Vào những năm 1920, các thành viên của khu tự trị Osage ở Mỹ bị ám sát một cách bí ẩn, làm dấy lên một cuộc điều tra lớn của FBI.",
    popularity: 2277.914,
    poster_path: "/1yTixpj3zakA1XFUq5PxR836HXO.jpg",
    release_date: "2023-10-18",
    title: "Vầng Trăng Máu",
    video: false,
    vote_average: 7.684,
    vote_count: 1301,
  },
  {
    adult: false,
    backdrop_path: "/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg",
    genre_ids: [16, 10751, 10402, 14, 35],
    id: 901362,
    original_language: "en",
    original_title: "Trolls Band Together",
    overview:
      "Sự xuất hiện đột ngột của John Dory, anh trai thất lạc đã lâu của Branch mở ra quá khứ bí mật được che giấu bấy lâu nay của Branch. Đó là quá khứ về một ban nhạc có tên BroZone từng rất nổi tiếng nhưng đã tan rã. Hành trình đi tìm lại các thành viên để làm một ban nhạc như xưa trở thành chuyến phiêu lưu âm nhạc đầy cảm xúc, tràn trề hi vọng về một cuộc sum họp gia đình tuyệt với nhất.",
    popularity: 1191.278,
    poster_path: "/zigNOyCkhmuBl16Fnd2s7SWZOmJ.jpg",
    release_date: "2023-10-12",
    title: "Quỷ Lùn Tinh Nghịch 3: Đồng Tâm Hiệp Nhạc",
    video: false,
    vote_average: 7.2,
    vote_count: 332,
  },
  {
    adult: false,
    backdrop_path: "/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg",
    genre_ids: [16, 35, 10751],
    id: 1075794,
    original_language: "en",
    original_title: "Leo",
    overview:
      "Adam Sandler là chú thằn lằn mang tên Leo trong bộ phim hài ca nhạc dành cho lứa tuổi mới lớn này. Bộ phim xoay quanh năm cuối cấp tiểu học qua góc nhìn từ chú thú kiểng của lớp.",
    popularity: 1016.769,
    poster_path: "/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg",
    release_date: "2023-11-17",
    title: "Chú Thằn Lằn Leo",
    video: false,
    vote_average: 7.572,
    vote_count: 510,
  },
];
